# Release Configuration
project_name: video-manager
report_sizes: true

before:
  hooks:
    - go mod download
    - go mod tidy
    - go run github.com/securego/gosec/v2/cmd/gosec@latest -quiet ./...
    - go run github.com/go-critic/go-critic/cmd/gocritic@latest check -enableAll ./...
    - go run github.com/google/osv-scanner/cmd/osv-scanner@latest -r .
    - go test -race .

builds:
  - id: default
    env: [CGO_ENABLED=0]
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]

upx:
  - ids: [default]
    enabled: true
    compress: best
    lzma: true
    brute: true
    goos: [linux, windows] # skip darwin (macOS 13.x Ventura is not support now)
    goarch: [amd64, arm64]

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files: [LICENSE, README.md]

nfpms:
  - maintainer: Jun Xiang <contact@ngjx.org>
    description: A local video manager.
    homepage: "https://github.com/caffeine-addictt/video-manager"
    license: MIT
    formats: [rpm, apk, termux.deb, deb, archlinux]
    dependencies: [git]

aurs:
  - maintainers: [Jun Xiang <contact@ngjx.org>]
    homepage: "https://github.com/caffeine-addictt/video-manager"
    license: MIT
    name: video-manager
    skip_upload: true
    depends: [go, git]
    optdepends:
      - "ffmpeg: for video transcoding"
      - "mpv: for video playback"
    backup: [/.video-manager]
    url_template: https://github.com/caffeine-addictt/video-manager/releases/{{ .Tag }}/{{ .ArtifactName }}
    package: |-
      #bin
      install -Dm755 'video-manager' ${pkgdir}/usr/bin/video-manager

      # completions
      # mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      # mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      # mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      # install -Dm644 "./completions/mybin.bash" "${pkgdir}/usr/share/bash-completion/completions/mybin"
      # install -Dm644 "./completions/mybin.zsh" "${pkgdir}/usr/share/zsh/site-functions/_mybin"
      # install -Dm644 "./completions/mybin.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/mybin.fish"

      # man pages
      # install -Dm644 "./manpages/mybin.1.gz" "${pkgdir}/usr/share/man/man1/mybin.1.gz"

release:
  ids: [default]
  draft: true
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  prerelease: auto
  mode: replace
  skip_upload: false

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  abbrev: 0
  filters:
    exclude: ["^*.md", "^*.ya?ml"]
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Improvements
      regexp: '^.*?(perf|refactor)(\(.+\))??!?:.+$'
      order: 2
    - title: Security issues
      regexp: ^.*?(S|s)ecurity.*?$
      order: 4
    - title: Others
      order: 999
