name: Run Test Suite

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: "Testing"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          language-version: 1.22.1

      - name: Install dependencies
        run: |
          set -xe
          go get .

      - name: Testing
        run: |
          set -xe
          go test
